config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions:      'sessions',
    omniauth_callbacks: 'omniauth_callbacks'
  } 
  devise_scope :user do
  root to: 'devise/sessions#home'
  end
  
   resources :products do
    collection do
      get :my_product
    end
    collection do
      get :add_quantity
      patch :update_quantity
    end
  end
  
  namespace :admin do
    resources  :dashboard, only: [:index, :destroy, :show]
    resources :categories
  end
  
  namespace :user do
    resources :carts, only: [:index]
    resources :cart_items
    resources :orders, only: [:create, :index, :show] do
      collection do
        get :user_order_details
      end
      collection do
        get :order_status
      end
    end
    resources :profiles
    resources :success
    resources :address, only: [:new, :create, :update]
    resources :payment do
      collection do
        get :create_payment_intent
      end
    end
  end
  get '/success', to: 'payment#success'
get '/cancel', to: 'payment#cancel'

#  get '/auth/facebook/callback', to: 'sessions#create'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
  end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items, dependent: :destroy
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   
	def create
		@total_price = 0
		@order = current_user.orders.create(invoice_number: Time.now.to_f.ceil)
		@cart_items = current_user.cart.cart_items
		@cart_items.each do |cart_item|
			@total_price = @total_price + cart_item.product.price * cart_item.quantity
			@order_items = @order.order_items.create(product_id: cart_item.product_id, quantity: cart_item.quantity)
		end
		@cart_items.delete_all
		@order.update(total_price: @total_price)
		OrderMailer.order_checkout(current_user,@order,@order_items).deliver_now
		flash[:notice] = "Your order has been successfully placed. Thank you for your purchase!"
		redirect_to orders_path
	end

	def index 
		@orders = Order.page(params[:page]).per(10).where(user_id: current_user.id)
		redirect_to dashboard_index_path, alert: 'you are unauthorized to access this page' and return if  current_user.is? :admin
	end

	def show   
		order_id = params[:id]
		# @order_items = OrderItem.where(order_id: order_id)
		@order = Order.where(id: order_id).first
		# if(@order.present?)
		if @order.blank?
			flash[:now] = "Order items not present"
			redirect_to orders_path and return
		end
		@order_items = @order.order_items.eager_load(:product)	
	end
end

app/controllers/user/address_controller.rb
class User::AddressController < ApplicationController
	def new
		@address = UserAddress.new
		respond_to do |format|
				format.js
		end
	end
	def create
		@address = UserAddress.new(locality: params[:user_address][:locality], street_no: params[:user_address][:street_no],
				plot_no: params[:user_address][:plot_no], district: params[:user_address][:district],
				state: params[:user_address][:state], nationality: params[:user_address][:nationality],
				pincode: params[:user_address][:pincode], user_id: current_user.id) 
		if(@address.save)
				flash[:message] = "Address added successfully"
				redirect_to user_profiles_path
		end
	end

	def update
		@address = UserAddress.where(user_id: current_user.id)
		@address.update(is_permanent: 0)
		@address.where(id: params[:id]).update(is_permanent: 1)
		@id = params[:id]
		respond_to do |format|
				format.js
			end
	end

    
end

app/controllers/user/cancel_conroller.rb
class User::CancelController < ApplicationController
	def index 
	end
end

app/controllers/user/cart_items_controller.rb
class User::CartItemsController < ApplicationController
  before_action :cart_items, only:[:create, :update]

  def create
    @product = Product.find(params[:product_id])
    binding.break
    if(@product.quantity > 0)
      @cart_id = current_user.cart.id
      if @cart_item 
        @cart_item.update(quantity: @cart_item.quantity+1)
      else
        @cart_item = CartItem.create(cart_id: @cart_id, product_id: params[:product_id],quantity: 1)
        #flash[:notice] = 'New product added'
      end
      @count = CartItem.where(cart_id: @cart_id).count
      flash[:message] = "Item added"
    else
      flash[:message] = "This product in temporarily unavailable"
    end
    respond_to do |format|
      format.js
    end

  end

  def destroy 
    id = params[:id]
    item = CartItem.find(id)
    item.destroy
    redirect_to user_carts_path
  end

  def update
    # if(params[:quantity]=="increment")
    #   @cart_item.quantity =  @cart_item.quantity+1
    # else
    #   @cart_item.quantity =  @cart_item.quantity-1
    #   if @cart_item.quantity==0
    #     @cart_item.delete
    #   end
    # end
    # @cart_item.save
    @cart_item.set_quantity params
    respond_to do |format|
      format.js
    end
  end

  private
  def cart_items
    @cart_item = current_user.cart.cart_items.find_by(product_id: params[:product_id])
  end
end

app/controllers/user/carts_controller.rb
class User::CartsController < ApplicationController
  def index
    if current_user.is? :user
      @cart_items = current_user.cart.cart_items
      @address = UserAddress.where(user_id: current_user.id)
      @role = current_user.roles.find_by_role("seller")
    else
     flash[:alert] = "You are unauthorized to access this page"
     redirect_to admin_dashboard_index_path
    end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    binding.pry
    @user = User.from_omniauth(request.env["omniauth.auth"])
    binding.break
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
    
  end

  def failure
    binding.break
    redirect_to root_path
  end

end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
	include OrderHelper
	# def create
	# 	@total_price = 0
	# 	@order = current_user.orders.create(invoice_number: Time.now.to_f.ceil)
	# 	@cart_items = current_user.cart.cart_items
	# 	@cart_items.each do |cart_item|
	# 		@total_price = @total_price + cart_item.product.price * cart_item.quantity
	# 		@order_items = @order.order_items.create(quantity: cart_item.quantity,
	# 			product_name: cart_item.product.name, price: cart_item.product.price)
	# 	end
	# 	@cart_items.delete_all
	# 	@order.update(total_price: @total_price)
	# 	OrderMailer.order_checkout(current_user,@order,@order_items).deliver_now
	# 	flash[:notice] = "Your order has been successfully placed. Thank you for your purchase!"
	# 	redirect_to user_orders_path
	# end

	def index 
		@orders = Order.page(params[:page]).per(10).where(user_id: current_user.id)
		@role = current_user.roles.find_by_role("seller") 
		redirect_to admin_dashboard_index_path, alert: 'you are unauthorized to access this page' and return if  current_user.is? :admin
	end

	def show   
		order_id = params[:id]
		# @order_items = OrderItem.where(order_id: order_id)
		@order = Order.find_by(id: order_id,user_id: current_user.id)
		# if(@order.present?)
		# if @order.blank?
		# 	flash[:now] = "Order items not present"
		# 	redirect_to user_orders_path and return
		# end
		if(@order.present?)
			@order_items = @order.order_items
		else
			flash[:alert] = "you are unauthorized to access this page"
			redirect_to admin_dashboard_index_path and return
		end	
	end

	# To view user's order details in seller page
	def user_order_details
		@product = current_user.products.pluck("id")
		#@order_id = OrderItem.where(product_id: @product).pluck("order_id")
		# @user = User.joins(:orders).where(orders:{id: @order_id})
		@user_order_details = User.joins(orders: :order_items).joins(:user_addresses)
		.where(order_items:{product_id: @product})
		.select('order_items.product_name','order_items.quantity','order_items.product_id',
			'order_items.price','users.id','users.first_name',
			'users.last_name','user_addresses.locality',
			'user_addresses.street_no','user_addresses.plot_no',
			'user_addresses.district','user_addresses.state',
			'user_addresses.nationality','user_addresses.pincode')
	end

	def order_status
		status_id = OrderStatus.statuses.key(params[:status])
		@order_status = UserStatus.where(user_id: params[:user_id]).where(product_id: params[:product_id])
		if ( @order_status.first.nil?)
			@track_data = UserStatus.create(user_id: params[:user_id], status_id: status_id, product_id: params[:product_id])
		else
			@track_data = UserStatus.where(user_id: params[:user_id], product_id: params[:product_id]).update(status_id: status_id)
		end
		OrderMailer.track_details(@track_data,params[:user_id]).deliver_now
		# i = 0
		# @status = []
		# while i<= status_id
		# 	@status << OrderStatus.statuses[i]
		# 	i=i+1
		# end
		# respond_to do |format|
		# 	format.js
		# end
	end
	
end

app/controllers/user/payment_controller.rb
class User::PaymentController < ApplicationController
  before_action :product_exists, only:[:create_payment_intent]

  def create_payment_intent
		@cart_items = current_user.cart.cart_items
    @lineItems=[]
		@cart_items.each do |cart_item|
      if(cart_item.product.quantity >= cart_item.quantity)
        if (@product_data.value?(cart_item.product.name))
          @product_id = @product_data.key(cart_item.product.name)
          @price_id = Stripe::Price.list({ product: @product_id }).data[0].id
        else
          price_amount = cart_item.product.price
          price_cents = (price_amount * 100).to_i
          # Create the product
          new_product = Stripe::Product.create({
            name: cart_item.product.name,
            type: 'service',
          })
          # Create the price and associate it with the product
          price = Stripe::Price.create({
            unit_amount: price_cents,  # Set the price in cents
            currency: 'inr',
            product: new_product.id,
          })
          @product_id = new_product.id
          @price_id = price.id
        end
        @lineItems.push(price: @price_id, quantity: cart_item.quantity)
        respond_to do |format|
          format.js
        end
      elsif (cart_item.product.quantity == 0)
        respond_to do |format|
          format.js { flash[:notice] = "#{cart_item.product.name} is out of stock .please remove from your cart" }
        end
      else
        respond_to do |format|
          format.js { flash[:notice] = "#{cart_item.product.quantity} unit amount of stock is  available for #{cart_item.product.name}" }
        end
      end
		end
  end 

  private
  def product_exists
    products = Stripe::Product.list({ limit: 3 })
    @product_data = {}
    products.data.each do |product|
      @product_data[product.id] = product.name
    end
  end
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
	before_action :user_params, only:[:update]
	before_action :set_role, only:[:index]

	def index
		if current_user.is? :admin
			authorize! :manage, :dashboard
			@user = User.find(session[:user_id])
		else
			authorize! :read, :dashboard
			@user = current_user
			@address = UserAddress.where(user_id: current_user.id)
		end
	end

	def edit
		@user = UserProfile.find_by_user_id(params[:id])
	end

	def update
    @user_profile = UserProfile.find(params[:id])
		if @user_profile.update(user_params)
			@user = current_user
			flash[:notice] = "Edited successfully"
			render 'index'
		else
			@user = current_user.user_profile
			flash[:alert] = @user_profile.errors.full_messages
			render 'edit'
		end
	end

	private

	def user_params
		params.require(:user_profile).permit(:address, :phone_number)
	end

	def set_role
    @role = current_user.roles.find_by_role("seller")
  end

end

app/controllers/user/success_controller.rb
class User::SuccessController < ApplicationController
	def index
		@total_price = 0
		@address_id = UserAddress.where(is_permanent: 1,user_id: current_user.id)
		@order = current_user.orders.create(invoice_number: Time.now.to_f.ceil, user_address_id: @address_id[0].id)
		@cart_items = current_user.cart.cart_items
		@role = current_user.roles.find_by_role("seller")
		products = [['Sl.No','Product', 'Quantity','Price']]
		i = 0
		@cart_items.each do |cart_item|
			array = []
			quantity = cart_item.product.quantity #product quantity
			@total_price = @total_price + cart_item.product.price * cart_item.quantity
			@order_items = @order.order_items.create(quantity: cart_item.quantity,
					product_name: cart_item.product.name, price: cart_item.product.price, product_id: cart_item.product.id)
			cart_item.product.update(quantity: quantity-cart_item.quantity)
			array << i+1
			array << cart_item.product.name
			array << cart_item.quantity
			array << "#{cart_item.product.price}/-"
			products << array 
		end
		products << ["","","Total","#{@total_price}/-"]
		@order.update(total_price: @total_price)
		pdf = Prawn::Document.new
		pdf.bounding_box([0, pdf.cursor], width: pdf.bounds.width / 2) do
			pdf.text "Order Details", align: :left, size: 30
			pdf.text "Hi #{current_user.first_name}", align: :left, size: 20
			pdf.text "Invoice number: #{@order.invoice_number}", align: :left, size: 15
			pdf.move_down 5
			pdf.text "Thanks for purchasing from Ekart", size: 12
		end
		pdf.move_up 20
	  pdf.bounding_box([pdf.bounds.width / 2, pdf.cursor], width: pdf.bounds.width / 2,size: 12) do
			pdf.draw_text "shipped to",at: [80, pdf.cursor], size: 14
			address_data = [
				["plot no:", "#{@address_id[0].plot_no}"],
				["street no:", "#{@address_id[0].street_no}"],
				["locality:", "#{@address_id[0].locality}"],
				["district:", "#{@address_id[0].district}"],
				["state:", "#{@address_id[0].state}"],
				["nationality:", "#{@address_id[0].nationality}"],
				["pincode:", "#{@address_id[0].pincode}"]
			]
			cell_width = pdf.bounds.width / 2 - 30 # Adjust the width of the individual cells
			pdf.table address_data, cell_style: { border_width: 0, width: cell_width, padding: [2, 0, 2, 0], inline_format: true, align: :center, size: 12 }
		end
		pdf.move_down 30
		pdf.text "Your purchased order is listed below", size: 12
		pdf.bounding_box([0, pdf.cursor], width: pdf.bounds.width) do
			order_data = products
			cell_width = pdf.bounds.width / 2 - 200 # Adjust the width of the individual cells
			pdf.table order_data, cell_style: { border_width: 0, width: cell_width, padding: [3, 0, 3, 0], inline_format: true, align: :center, size: 12,float: :left }
		end
		pdf.move_down 50
		pdf.text " Thank You", size: 12
		pdf.render_file(Rails.root.join('public', "order_#{@order.id}.pdf"))	
		SendMailJob.perform_later(current_user, @order, @order_items)
		#OrderMailer.order_checkout(current_user,@order,@order_items).deliver_now
		@cart_item_quantity = CartItem.where(cart_id: current_user.cart.id).count
		@cart_items.delete_all
	end
end

app/controllers/user/user_controller.rb
module User
	class UserController < ActionController::Base
		
	end
end

app/helpers/order_helper.rb
module OrderHelper
	def is_complete(status_id, product_id)
		@status = UserStatus.where(user_id: current_user.id,status_id: status_id, product_id: product_id)
		if !@status.first.nil?
			return true
		else 
			return false
		end
	end
end

app/views/user/orders/_user_order_status.html.erb
<li class="list-inline-item items-list">
  <% if locals[:is_completed]%>
    <p class="py-1 px-2 rounded" style="background-color: orange"><%= locals[:status] %></p>
  <% else %>
    <p class="py-1 px-2 rounded" ><%= locals[:status] %></p>
  <% end %>
</li>

app/views/user/orders/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success">
		<%= flash[:notice] %>
	</div>
<% end %>
<section style="background-color: #eee;">
	<div class="container">
		<%if current_user.orders.present?%>
			<h1>Orders</h1>
			<div class="row">
				<table class="table" id="orders_table">
					<thead>
						<tr>
							<th scope="col">Invoice number</th>
							<th scope="col">Total Price</th>
							<th scope="col">Details</th>
						</tr>
					</thead>
					<tbody>
						<% @orders.each do |order| %>
							<tr>
								<td scope="row"><%= order.invoice_number%></th>
								<td><%= order.total_price %></td>
								<td>  
									<%= link_to user_order_path(order.id), method: :get do %>
    								<i class="fa fa-eye"></i> 
  								<% end %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
				<%= paginate @orders %>
			</div> 
		<%else%>
			<h3>You have no orders to display</h3>
		<%end%>
	</div>
	<script>
	$(document).ready( function () {
		$('#orders_table').DataTable();
	});
</script>
</section>

app/views/user/orders/order_status.js.erb
var status_id = '<%=j @track_data[0].status_id%>';

var data = '<%=j @status %>'
console.log('<%=j @status %>')
alert('<%=j @status[0] %>')

data.forEach(entry => {
  $("#status_dropdown option:contains( " + entry + ")").attr("disabled", "disabled");
});

app/views/user/orders/show.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success"">
		<%= flash[:notice] %>
	</div>
<% end %>
<div class="container">
	<h1>Order Items</h1>
	<section style="background-color: #eee;">
		<div class="container py-5">
			<% @order_items.each do |order_item| %>
				<div class="row justify-content-center mb-3">
					<div class="col-md-12 col-xl-10">
						<div class="card shadow-0 border rounded-3">
							<div class="card-body">
								<div class="row">
									<div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
										<div class="bg-image hover-zoom ripple rounded ripple-surface">
											<img src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/img%20(4).webp"
												class="w-100" />
											<a href="#!">
												<div class="hover-overlay">
												<div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
												</div>
											</a>
										</div>
									</div>
									<div class="col-md-6 col-lg-6 col-xl-6">
										<h5><%= order_item.product_name%></h5>
										<div class="mt-1 mb-0 text-muted small">
										<span>price: <%= order_item.price %>  </span>
										</div>
										<div class="mt-1 mb-0 text-muted small">
										<span>Quantity: <%= order_item.quantity %></span>
										</div>
										<br/>
										<div class="row">
											<div class="col-lg-12">
												<div class="horizontal-timeline">
													<ul class="list-inline items d-flex justify-content-between">
														<%= render "user_order_status", locals: {status: "pending", is_completed: is_complete(0, order_item.product_id)}%>
														<%= render "user_order_status", locals: {status: "confirmed", is_completed: is_complete(1, order_item.product_id)}%>
														<%= render "user_order_status", locals: {status: "shipped", is_completed: is_complete(2, order_item.product_id)}%>
														<%= render "user_order_status", locals: {status: "delivered", is_completed: is_complete(3, order_item.product_id)}%>
														<%= render "user_order_status", locals: {status: "cancelled", is_completed: is_complete(4, order_item.product_id)}%>
													</ul>
												</div>
											</div>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			<% end %>
			<div class="row">
				<div class="col-md-12">
					<div style="text-align: center">
						<%= button_to "back", user_orders_path, method: :get, class: "btn btn-warning btn-lg" %>
					</div>
				</div>
			</div> 
		</div>
	</section>
</div>

app/views/user/orders/user_order_details.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success"">
		<%= flash[:notice] %>
	</div>
<% end %>
<div class="container">
	<h1>User's Order Items</h1>
	<div class="row">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">User Name</th>
					<th scope="col">Product Name</th>
					<th scope="col">Quantity</th>
          <th scope="col">Address</th>
          <th scope="col">Status</th>
				</tr>
			</thead>
			<tbody>
				<% @user_order_details.each do |user| %>
 					<%
						user_status = UserStatus.find_by(product_id: user.product_id, user_id: user.id)
						status_id = user_status.status_id
						i=0
						status = []
						while i	<= status_id
							status << OrderStatus.statuses[i]
							i+=1
						end
					%> 
					<tr>
						<td scope="row"><%= user.first_name%> <%= user.last_name%></th>
						<td><%= user.product_name %></td>
						<td><%= user.quantity %></td>
						<td>plot-no:<%= user.plot_no %>,street-no:<%= user.street_no%>,
						<%= user.locality%>,<%= user.district%>,
						<%= user.state%>,<%= user.nationality %>,<%= user.pincode %></td>
						<td>
						<%= select_tag(
								'status',
								options_for_select(
									OrderStatus.statuses.values,
									disabled: status
									
								),
								class: 'input-block-level chzn-select hiring_stage_dropdown',
								id: 'status_dropdown',
								data: {
									remote: true,
									url: "/user/orders/order_status?user_id=#{user.id}&product_id=#{user.product_id}",
									method: 'get',
								}
								) %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div> 
</div>