config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions:      'sessions',
    omniauth_callbacks: 'omniauth_callbacks'
  } 
  devise_scope :user do
  root to: 'devise/sessions#home'
  end
  
   resources :products do
    collection do
      get :my_product
    end
    collection do
      get :add_quantity
      patch :update_quantity
    end
  end
  
  namespace :admin do
    resources  :dashboard, only: [:index, :destroy, :show]
    resources :categories
  end
  
  namespace :user do
    resources :carts, only: [:index]
    resources :cart_items
    resources :orders, only: [:create, :index, :show] do
      collection do
        get :user_order_details
      end
      collection do
        get :order_status
      end
    end
    resources :profiles
    resources :success
    resources :address, only: [:new, :create, :update]
    resources :payment do
      collection do
        get :create_payment_intent
      end
    end
  end
  get '/success', to: 'payment#success'
get '/cancel', to: 'payment#cancel'

#  get '/auth/facebook/callback', to: 'sessions#create'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
  end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	before_action :select_all_user, only:[:index, :destroy] 

	def index
		if current_user.nil?
			redirect_to new_user_session_path
		else
			if current_user.is? :admin
				authorize! :manage, :dashboard
				authorize! :access, :admin
				
				# Additional logic for admin dashboard
			elsif current_user.is? :user
				authorize! :read, :dashboard
				@user = current_user
				flash[:alert] = "you are unauthorized to access this page"
				redirect_to products_path
			else
				sign_up_path
			end
		end
	end

	def show
		# view customer profile
		@user = User.find(params[:id])
		session[:user_id] = @user.id 
		@address = UserAddress.where(user_id: @user.id)
		render 'user/profiles/index'
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to admin_dashboard_index_path
	end

	private
	def select_all_user
		role_id = Role.where(role: "user").first.id
		@users = User.joins(:user_roles).where(user_roles: {role_id: role_id})
	end
end

app/views/admin/dashboard/_table.html.erb
<table class="table" id="user_table">
	<thead>
		<tr>
			<th scope="col">Name</th>
			<th scope="col">Type</th>
			<th scope="col">Email</th>
			<th scope="col">action</th>
		</tr>
	</thead>
	<tbody>	
		<% @users.each do |user| %>
			<%if user.deactivated%>
				<tr style="background-color:#F2F3F4 ">
					<td scope="row"><%= user.first_name %></th>
					<td><%= user.roles.pluck(:role).join(',')%></td>
					<td><%= user.email %></td>
					<td>
						<div class="button-group">
							<%= button_to "delete", admin_dashboard_path(user.id), class: "btn btn-danger btn-sm", method: :delete  %>
							<%= button_to "show", admin_dashboard_path(user.id), class: "btn btn-success btn-sm", method: :get  %>
						</div>
					</td>
				</tr>
			<%else%>
				<tr >
					<td scope="row"><%= user.first_name %></th>
					<td><%= user.roles.pluck(:role).join(',')%></td>
					<td><%= user.email %></td>
					<td>
						<div class="button-group">
							<%= button_to "delete", admin_dashboard_path(user.id), class: "btn btn-danger btn-sm", method: :delete  %>
							<%= button_to "show", admin_dashboard_path(user.id), class: "btn btn-success btn-sm", method: :get  %>
						</div>
					</td>
				</tr>
			<%end%>
		<% end %> 
	</tbody>
</table>

app/views/admin/dashboard/index.html.erb
 <% if flash[:alert] %>
	<div class="alert alert-danger">
		<%= flash[:alert] %>
	</div>
<% end %>
<div class="container py-5 h-100">
	<h3>Dashboard</h3>
	<div class="row">
		<div class="col-lg-3 col-sm-12 col-xs-12">
			<div class="card" style="width: 18rem;height: 139px;">
				<div class="card-body">
					<h2 class="card-title"><%= User.count%></h2>
					<h4 class="card-text">Total Customer</h4>
				</div>
			</div>
		</div> 
		<div class="col-lg-3 col-sm-12 col-xs-12">
			<div class="card" style="width: 18rem;">
				<div class="card-body">
					<h2 class="card-title"><%= Category.count%></h2>
					<h4 class="card-text">Available Categories</h4>
					<%= link_to 'more details', admin_categories_path%>
				</div>
			</div>
		</div> 
		<div class="col-lg-3 col-sm-12 col-xs-12">
			<div class="card" style="width: 18rem;">
				<div class="card-body">
					<h2 class="card-title"><%= Product.count%></h2>
					<h4 class="card-text">Available Products</h4>
					<%= link_to 'more details', products_path%>
				</div>
			</div>
		</div>      
		<div class="col-lg-3 col-sm-12 col-xs-12">
			<div class="card" style="width: 18rem;height: 139px;">
				<div class="card-body">
					<h2 class="card-title"><%= Order.sum('total_price')%></h2>
					<h4 class="card-text">Total Revenue</h4>
				</div>
			</div>
		</div>    
	</div>
	<hr class="my-4">
	<div class="row d-flex justify-content-center align-items-center h-100">
		<div class="col-12">
			<div class="card card-registration card-registration-2" style="border-radius: 15px;">
				<div class="card-body p-0">
					<div class="row g-0">
						<div class="col-lg-12">
							<div class="p-5">
								<div class="d-flex justify-content-between align-items-center mb-5">
									<h1 class="fw-bold mb-0 text-black">Customer Details</h1>
								</div>
								<%= render "table" %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready( function () {
    $('#user_table').DataTable();
	});
</script>








 

app/views/admin/dashboard/index.js.erb
  $(document).ready(function() {
    $('#user_table').dataTable({
    'iDisplayLength': 2,//Set Row Per Page
    "bFilter": false,//Remove Search
    "bPaginate" : false,//Remove Pagination
    "bInfo": false,//Remove Page Info
    "bLengthChange":false,//Show per Page Dropdown Remove
    "columnDefs": [ { "targets": 0, "orderable": false } ],//Remove Colum Orderable(Here Col 0 Remove)
    "aoColumns": [{ "asSorting": [] },{ "asSorting": [ "asc" ] },{ "asSorting": [ "desc", "asc" ] },{ "asSorting": [ "desc" ] },null],//Set Colum Order By ASC Or DSC
    "sPaginationType": "full_numbers"//Full Pagination
    });
    $('#add_address').html("<%= escape_javascript render('form', user: @users) %>")
  });