config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions:      'sessions',
    omniauth_callbacks: 'omniauth_callbacks'
  } 
  devise_scope :user do
  root to: 'devise/sessions#home'
  end
  
   resources :products do
    collection do
      get :my_product
    end
    collection do
      get :add_quantity
      patch :update_quantity
    end
  end
  
  namespace :admin do
    resources  :dashboard, only: [:index, :destroy, :show]
    resources :categories
  end
  
  namespace :user do
    resources :carts, only: [:index]
    resources :cart_items
    resources :orders, only: [:create, :index, :show] do
      collection do
        get :user_order_details
      end
      collection do
        get :order_status
      end
    end
    resources :profiles
    resources :success
    resources :address, only: [:new, :create, :update]
    resources :payment do
      collection do
        get :create_payment_intent
      end
    end
  end
  get '/success', to: 'payment#success'
get '/cancel', to: 'payment#cancel'

#  get '/auth/facebook/callback', to: 'sessions#create'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
  end

app/models/product.rb
class Product < ApplicationRecord
	include Kaminari::PageScopeMethods
	validates :name, presence: true
	validates :price, presence: true
	belongs_to :user
	has_many :cart_items, dependent: :destroy
	has_many :category_products, dependent: :destroy
	has_many :categories, through: :category_products
	attr_accessor :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category_id, only:[:index]
  before_action :set_role, only:[:index, :new, :my_product]

  def index

    if @category_id.present?
      @products = Product.page(params[:page]).per(10).joins(:category_products).where(category_products: { category_id: @category_id }).distinct
      # will filter product of other seller's except own product
      if !@role.nil?
        @products =  @products.where.not(products: {user_id: current_user.id}).page(params[:page]).per(10)
      end
    else
      @products = Product.page(params[:page]).per(10)
      # will filter product of other seller's except own product
      if !@role.nil?
        @products = @products.where.not(user_id: current_user.id)
      end
    end
    if params[:search].present?
      @searched_product = params[:search]
      if @category_id.blank?
        @products = Product.page(params[:page]).per(10).where("name LIKE?","%#{@searched_product}%")
        # will filter product of other seller's except own product
        if !@role.nil?
          @products = @products.where.not(user_id: current_user.id)
        end
      else
        @products = Product.page(params[:page]).per(10).joins(category_products: :category).where('products.name LIKE?',"%#{@searched_product}%").where(category_products:{category_id: @category_id})
        # will filter product of other seller's except own product
        if !@role.nil?
          @products = @products.where.not(products: {user_id: current_user.id})
        end
      end
    end
   
  end

  def new
    @product = Product.new
    #authorize wheather the user is seller or not
    if @role.nil?
      authorize! :new, @product
    end
  end

  def create
    @product = Product.create(name: params[:product][:name], price: params[:product][:price],user_id: current_user.id,quantity: params[:product][:quantity])
    @categories = params[:category]
    @categories.each do |category|
      @product.category_products.create(category_id: category)
    end
    redirect_to my_product_products_path
    
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "product deleted"
    end
    if current_user.is? :admin
      redirect_to products_path
    else
      redirect_to my_product_products_path
    end
  end

  def edit
    @product = Product.find(params[:id])
    @category_id = current_user.products.first.category_products.pluck(:category_id)
  end

  def update
    @product = Product.find(params[:id])
    if(params[:product][:quantity].nil?)
      if @product.update(name: params[:product][:name], price: params[:product][:price],user_id: current_user.id)
        @categories = params[:category]
        @categories.each do |category|
          @product.category_products.create(category_id: category)
        end
        flash[:notice] = "Edited successfully"
        if current_user.is? :admin
          redirect_to products_path
        else
          redirect_to my_product_products_path
        end
      end
      else
        @product.update(quantity: params[:product][:quantity])
         flash[:notice] = "Edited successfully"
         redirect_to my_product_products_path
      end
  end

  def my_product
    if @role.nil?
      flash[:alert] = "You have no authorization to access this page"
      redirect_to products_path
    else
      @product = Product.new
      @products = Product.page(params[:page]).per(10).where(user_id: current_user.id)
      if params[:search].present?
        @searched_product = params[:search]
        @products = Product.page(params[:page]).per(10).where("name LIKE?","%#{@searched_product}%").where(user_id: current_user.id)
      end
    end
  end

  def add_quantity
    @id = params[:id]
    @product = Product.find(@id)
    respond_to do |format|
      format.js
    end
  end

  def update_quantity
    binding.break
  end

  private
  def set_category_id
    @category_id = params[:category_id]
  end

  def set_role
    @role = current_user.roles.find_by_role("seller")
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_admin_product.html.erb
<div class="row">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Product Name</th>
				<th scope="col">Price</th>
				<th scope="col">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td scope="row"><%= product.name%></th>
					<td><%= product.price %></td>
					<td>
						<div class="button-group">
							<%= button_to product_path(product.id), method: :delete, class: "btn btn-danger btn-sm" do %>
								<i class="fas fa-trash"></i> 
							<% end %>
							<%= button_to edit_product_path(product.id), method: :get, class: "btn btn-warning btn-sm" do %>
								<i class="fas fa-edit"></i> 
							<% end %>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div> 


	<%
=begin%>
 <div class="col-md-4">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">Seller</h5>
				<%= form_tag products_path, method: :get, class: "d-flex" do %>
					<%= hidden_field_tag :category_id, @category_id %>
					<%= text_field_tag :search, nil, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" }, id: "search_product" %>
					<%= button_tag "Search", type: :submit, class: "btn btn-outline-success" %>
				<% end %> 
			</div>
		</div> 
<%
=end%>
	</div>

app/views/products/_category.html.erb
<div class="col-md-2 px-0">
	<nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
		<div class="position-sticky">
			<div class="list-group list-group-flush mx-3 mt-2">
				<h3>Category</h3>
				<%= link_to 'all product', products_path%>
				<br/>
				<% Category.all.each do |category| %>
					<%= link_to category.category_name, products_path + "?category_id=#{category.id}",method: :get%>
					<br/>
				<% end %>
			</div>
		</div>
	</nav>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="col-auto flex-grow-1">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: "form-control", placeholder: "quantity"%>
  </div>
  <br/>
  <div class="col-auto flex-grow-1">
    <%=f.submit%>
  </div>
<%end%> 

app/views/products/add_quantity.js.erb
$('#edit_quantity').html("<%= escape_javascript render('form', product: @product) %>")

app/views/products/edit.html.erb
<div class="mt-4">
	<div class="container">
	
	<% if flash[:notice] %>
		<div class="alert alert-success">
			<%= flash[:notice] %>
		</div>
	<% end %>

	<% if flash[:alert] %>
		<div class="alert alert-danger">
      <% flash[:alert].each do |notice| %>
        <%= notice %>
        <br/>
      <%end%>
		</div>
	<% end %>
	<%= form_for(@product) do |f| %>
		<div class="col-auto flex-grow-1">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control"%>
		</div>
		<br/>
		<div class="col-auto flex-grow-1">
			<%= f.label :price %>
			<%= f.text_field :price, class: "form-control" %>
		</div>
		<br/>
		<div class="col-auto flex-grow-1">
			<%= f.label :quantity %>
			<%= f.text_field :quantity, class: "form-control" %>
		</div>
		<br/>
		<div class="col-auto flex-grow-1">
			<%= f.label :Category%>
			<%= select_tag 'category', options_from_collection_for_select(Category.all,"id","category_name", @category_id), prompt: "Select a Category",:multiple => true, class: 'form-control' %>
		</div>
		<br/>
		<div class="col-auto", style="text-align:center">
			<%= f.submit "update", class: "btn btn-warning btn-lg" %>
		</div>
	<%end%> 
	</div>
</div>

app/views/products/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success">
		<%= flash[:notice] %>
	</div>
<% end %>
<% if flash[:alert] %>
	<div class="alert alert-danger">
		<%= flash[:alert] %>
	</div>
<% end %>
<div class="row mx-0">
<%=render 'category'%>
	<div class="col-md-10 px-0">
		<div class="container">
			<%if @products.blank?%>
				<div class="col-sm-6">
					<h1 style="text-align:center">There is no product available</h1>
				</div>
			<%else%>
				<h1>Product Details</h1>
				<% if !@role.nil? %>
					<div class="d-flex justify-content-between align-items-center mb-5">
						<h6 class="mb-0 text-muted">
							<%= link_to "Add Product", new_product_path, class: "btn btn-primary"%>
							<%= link_to "My Products ", my_product_products_path, class: "btn btn-primary"%>
						</h6>
					</div>
				<%end%>
				<%= form_tag products_path, method: :get, class: "d-flex" do %>
					<%= hidden_field_tag :category_id, @category_id %>
					<%= text_field_tag :search, nil, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" }, id: "search_product" %>
					<%= button_tag "Search", type: :submit, class: "btn btn-outline-success" %>
				<% end %> 				

				<div class="row">
					<%if current_user.is? :user%>
						<% @products.each do |product| %>
							<div class="col-sm-6">
								<div class="card">
									<div class="card-body">
										<%= product.name%> <br/>
										<%= product.price %> <br/>
										<%= button_to user_cart_items_path(product_id: product.id), class: 'btn btn-primary btn-sm add_to_cart', title: "add to cart", remote: true do %>
  										<i class="fa fa-shopping-cart"></i> 
										<% end %>
										</div>
								</div>
							</div>
						<% end %>
						<%else%>
						<%=render 'admin_product'%>
					<%end%>
					<%= paginate @products %>
				</div>
			<%end%>
		</div>
	</div>
</div>
<script>
	$(".add_to_cart").hover(function(){
		$(".add_to_cart").tooltip({
		position: { my: "left+15 center", at: "right center"}
		})
  })
</script>

app/views/products/my_product.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success">
		<%= flash[:notice] %>
	</div>
<% end %>
<% if flash[:alert] %>
	<div class="alert alert-danger">
		<%= flash[:alert] %>
	</div>
<% end %>
<div class="row mx-0">
<%=render 'category'%>
	<div class="col-md-10 px-0">
		<div class="container">
			<%if @products.blank?%>
				<div class="col-sm-6">
					<h1 style="margin-top: 156px;margin-left: 211px;">You don't have any product. Please add</h1>
				</div>
				<div class="d-flex justify-content-between align-items-center mb-5">
					<h6 class="mb-0 text-muted" style="margin-left: 310px;margin-bottom: -43px;">
						<%= link_to "Add Product", new_product_path, class: "btn btn-primary"%>
					</h6>
				</div>
			<%else%>
				<h1>My Product</h1>
				<% if !@role.nil? %>
					<div class="d-flex justify-content-between align-items-center mb-5">
						<h6 class="mb-0 text-muted">
							<%= link_to "Add Product", new_product_path, class: "btn btn-primary"%>
						</h6>
					</div>
				<%end%>
				<%= form_tag my_product_products_path, method: :get, class: "d-flex" do %>
					<%= hidden_field_tag :category_id, @category_id %>
					<%= text_field_tag :search, nil, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" }, id: "search_product" %>
					<%= button_tag "Search", type: :submit, class: "btn btn-outline-success" %>
				<% end %> 
				<br/>
				<div class="row">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Product Name</th>
								<th scope="col">Price</th>
								<th scope="col">Quantity</th>
								<th scope="col">Action</th>
							</tr>
						</thead>
						<tbody>
							<% @products.each do |product| %>
								<tr>
									<td scope="row"><%= product.name%></th>
									<td><%= product.price %></td>
									<td><%= product.quantity %></td>
									<td>
										<div class="button-group">
											<%= link_to product_path(product.id), method: :delete, class: "btn btn-danger btn-sm delete", title: "delete" do %>
												<i class="fa fa-trash" aria-hidden="true"></i> 
											<% end %>
											
											<%= link_to edit_product_path(product.id), method: :get, class: "btn btn-warning btn-sm edit", title: "Edit" do %>
												<i class="fa fa-edit" aria-hidden="true"></i> 
											<% end %>
											<%= link_to add_quantity_products_path(id: product.id), method: :get, id: "add_quantity#{product.id}", class: "btn btn-success add_quantity", 
											title: "add quantity",
											data: {
												value: product.id,
												bs_toggle: 'modal',
												bs_target: "#exampleModal",
												remote: true
											} do %>
												<i class="fas fa-sort-amount-up"></i>
											<% end %>
										</div>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div> 
				<div class="row">
					<div class="col-md-12">
						<div style="text-align: center">
						<%= link_to products_path, class: "btn btn-warning btn-lg" do %>
  						<i class="fa fa-arrow-left"></i> Back
						<% end %>
							
						</div>
					</div>
				</div>
				<%= paginate @products %>
			<%end%>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add quantity</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="edit_quantity">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	 </div>
    </div>
  </div>
</div>

<script>
	$(".delete").hover(function(){
		$(".delete").tooltip()
  })
	$(".edit").hover(function(){
		$(".edit").tooltip()
  })
	$(".add_quantity").hover(function(){
		$(".add_quantity").tooltip()
  })
</script>

app/views/products/new.html.erb
<div class="mt-4">
	<div class="container">
		<h3>Add Product</h3>
		<% if flash[:notice] %>
		<div class="alert alert-success">
			<%= flash[:notice] %>
		</div>
		<% end %>

		<% if flash[:alert] %>
		<div class="alert alert-danger">
		<% flash[:alert].each do |notice| %>
			<%= notice %>
			<br/>
		<%end%>
		</div>
		<% end %>
		<%= form_for(@product) do |f| %>
			<div class="col-auto flex-grow-1">
				<%= f.label :product %>
				<%= f.text_field :name, class: "form-control", placeholder: "product name"%>
			</div>
			<br/>
			<div class="col-auto flex-grow-1">
				<%= f.label :price %>
				<%= f.text_field :price, class: "form-control", placeholder: "product price"%>
			</div>
			<br/>
			<div class="col-auto flex-grow-1">
				<%= f.label :quantity %>
				<%= f.text_field :quantity, class: "form-control", placeholder: "product quantity"%>
			</div>
			<br/>
			<div class="col-auto flex-grow-1">
				<%= f.label :Category%>
				<%= select_tag 'category', options_from_collection_for_select(Category.all,"id","category_name"),  :multiple => true, class: 'form-control'%>
			</div>
			<br/>
			<div class="col-auto", style="text-align:center">
				<%= f.submit "add", class: "btn btn-primary btn-lg" %>
			</div>
		<%end%> 
		<br/>
		<div class="col-auto", style="text-align:center">
			<%= button_to "back", products_path, method: :get, class: "btn btn-warning btn-lg" %>
		</div>
	</div>
</div>

app/views/products/search.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-sm-6">
			<div class="card">
				<div class="card-body">
					<%= product.name%> <br/>
					<%= product.price %> <br/>
					<%= button_to "Add Cart", cart_items_path + "?product_id=#{product.id}",  method: :post %>
				</div>
			</div>
		</div>
	<% end %>
</div>